---
name: Diff
description: Using diff to diff files/directories
author: ixxeL
inputs:
  source:
    required: true
    description: first file/dir to compare
  target:
    required: true
    description: second file/dir to compare
  exclude-regexp:
    required: false
    default: "spec.template.metadata.annotations.checksum"
    description: regexp to exclude from comparison

runs:
  using: composite
  steps:
    - id: dyff
      run: |
        set +e
        echo -e "${BLUE}[ STEP - DIFF ] > Diffing files with Diff${BLANK}"
        echo -e "${CYAN}[ INFO ] > Using source dir/file ${PURPLE}${{ inputs.source }}${CYAN} and target dir/file ${PURPLE}${{ inputs.target }}${BLANK}"

        echo '```diff' > diff.md
        if [ -f "${{ inputs.source }}" ] && [ -f "${{ inputs.target }}" ]
        then
          echo -e "${CYAN}[ INFO ] > Files one to one${BLANK}"
          RESULT=$(diff ${{ inputs.source }} ${{ inputs.target }} --color=always --unified=10)
          echo "${RESULT}"
          diff ${{ inputs.source }} ${{ inputs.target }} --color=never --unified=10 >> diff.md || true
          MAX_SIZE=65000
          CURRENT_SIZE=$(wc -c < diff.md)
          if [ "$CURRENT_SIZE" -gt "$MAX_SIZE" ]; then
            echo -e "${RED}[ WARNING ] > Diff output exceeds ${MAX_SIZE} characters, truncating...${BLANK}"
            head -c 64500 diff.md > diff.tmp
            echo -e "\n[Truncated: Diff output was too large]" >> diff.tmp
            mv diff.tmp diff.md
          fi
          echo " " >> diff.md
        elif [[ "${{ inputs.source }}" == *"*"* ]] && [[ "${{ inputs.target }}" == *"*"* ]]
        then
          echo -e "${CYAN}[ INFO ] > Pattern${BLANK}"
          SOURCE_SUFFIX=$(echo "${{ inputs.source }}" | sed 's/.*\*//')
          TARGET_PREFIX=$(echo "${{ inputs.target }}" | sed 's/\*.*//')
          TARGET_SUFFIX=$(echo "${{ inputs.target }}" | sed 's/.*\*//')

          for source_file in ${{ inputs.source }}
          do
            echo -e "${CYAN}[ INFO ] > found file ${PURPLE}$source_file${BLANK}"
            base_name=$(basename "$source_file" "$SOURCE_SUFFIX")
            echo -e "${CYAN}[ INFO ] > Base name extracted ${PURPLE}$base_name${BLANK}"
            target_file="${TARGET_PREFIX}${base_name}${TARGET_SUFFIX}"
            echo -e "${CYAN}[ INFO ] > Target file ${PURPLE}$target_file${BLANK}"

            if [ -f "$target_file" ]; then
              RESULT=$(diff ${source_file} ${target_file} --color=always --unified=10)
              echo "${RESULT}"
              diff ${source_file} ${target_file} --color=never --unified=10 >> diff.md || true
              MAX_SIZE=65000
              CURRENT_SIZE=$(wc -c < diff.md)
              if [ "$CURRENT_SIZE" -gt "$MAX_SIZE" ]; then
                echo -e "${RED}[ WARNING ] > Diff output exceeds ${MAX_SIZE} characters, truncating...${BLANK}"
                head -c 64500 diff.md > diff.tmp
                echo -e "\n[Truncated: Diff output was too large]" >> diff.tmp
                mv diff.tmp diff.md
              fi
              echo " " >> diff.md
            else
              echo -e "${RED}[ ERROR ] > Target file $target_file not found${BLANK}"
              exit 1
            fi
          done
        fi
        echo '```' >> diff.md
      shell: bash
      env:
        RED: \033[1;31m
        GREEN: \033[1;32m
        YELLOW: \033[1;33m
        BLUE: \033[1;34m
        PURPLE: \033[1;35m
        CYAN: \033[1;36m
        BLANK: \033[0m
