---
name: Encrypt password
description: Encrypting password with gpg
author: ixxeL
inputs:
  hash-secret:
    required: true
    description: secret hash
  token:
    required: true
    description: token to encrypt
outputs:
  ENCRYPTED_TOKEN:
    description: chart name
    value: ${{ steps.encrypt-pwd.outputs.ENCRYPTED_TOKEN }}

runs:
  using: composite
  steps:
    - id: encrypt-pwd
      run: |
        echo -e "${BLUE}[ STEP - ENCRYPT PWD ] > Encrypting password with gpg${BLANK}"
        echo -e "${CYAN}[ INFO ] > gpg version.${BLANK}"
        gpg --version

        echo -e "${YELLOW}[ EXECUTING ] > Encrypting password${BLANK}"
        SECRET="${{ inputs.hash-secret }}"
        KEY="${{ inputs.token }}"
        echo "KEY = $KEY"

        ENCRYPTED_TOKEN=$(gpg --symmetric --batch --passphrase "$SECRET" --output - <(echo "$KEY") | base64 -w0)
        if [[ $? = 0 ]]
        then
          echo -e "${GREEN}[ SUCCESS ] > Encryption success ! ${BLANK}"
        else
          echo -e "${RED}[ FAIL ] > Encryption failed ! ${BLANK}"
          exit 1
        fi
        echo "ENCRYPTED_TOKEN=$ENCRYPTED_TOKEN" >> $GITHUB_OUTPUT
      shell: bash
      env:
        RED: \033[1;31m
        GREEN: \033[1;32m
        YELLOW: \033[1;33m
        BLUE: \033[1;34m
        PURPLE: \033[1;35m
        CYAN: \033[1;36m
        BLANK: \033[0m
