---
name: Pre-commit
description: Running pre-commit
author: ixxeL
inputs:
  extra_args:
    description: options to pass to pre-commit run
    required: false
    default: "--all-files"

runs:
  using: composite
  steps:
    - id: prepare
      run: |
        if [[ $(pre-commit --version) ]]
        then
          echo -e "${CYAN}[ INFO ] > pre-commit already installed${BLANK}"
        else
          python -m pip install pre-commit
        fi
        python -m pip freeze --local
      shell: bash
      env:
        RED: \033[1;31m
        GREEN: \033[1;32m
        YELLOW: \033[1;33m
        BLUE: \033[1;34m
        PURPLE: \033[1;35m
        CYAN: \033[1;36m
        BLANK: \033[0m
    - id: prepare-action-validator
      run: |
        if [[ $(action-validator --version) ]]
        then
          echo -e "${CYAN}[ INFO ] > action-validator already installed${BLANK}"
        else
          VERSION=$(curl -sSLf https://github.com/mpalmer/action-validator/releases | grep -oE "v[0-9]{1,2}\.[0-9]{1,2}\.[0-9]{1,2}" | uniq | sort -rV | head -1)
          echo -e "${YELLOW}[ EXECUTING ] > Installing action-validator version $VERSION${BLANK}"
          curl -sSfLO "https://github.com/mpalmer/action-validator/releases/download/${VERSION}/action-validator_linux_amd64"
          chmod +x action-validator_linux_amd64
          sudo mv action-validator_linux_amd64 /usr/local/bin/action-validator
        fi
      shell: bash
      env:
        RED: \033[1;31m
        GREEN: \033[1;32m
        YELLOW: \033[1;33m
        BLUE: \033[1;34m
        PURPLE: \033[1;35m
        CYAN: \033[1;36m
        BLANK: \033[0m
    - id: pre-comit
      run: |
        pre-commit run --show-diff-on-failure --color=always ${{ inputs.extra_args }}
      shell: bash
      env:
        RED: \033[1;31m
        GREEN: \033[1;32m
        YELLOW: \033[1;33m
        BLUE: \033[1;34m
        PURPLE: \033[1;35m
        CYAN: \033[1;36m
        BLANK: \033[0m
