---
name: Github Pull Request origin
description: Check the origin Pull Request for a specific commit
author: ixxeL
inputs:
  commit:
    required: false
    description: ID of the current run to cancel
    default: ${{ github.sha }}
outputs:
  PR_NUMBER:
    description: PR number
    value: ${{ steps.gh-pr-origin.outputs.PR_NUMBER }}

runs:
  using: composite
  steps:
    - id: gh-pr-origin
      run: |
        set +e
        echo -e "${BLUE}[ STEP - CHECK PR ORIGIN ] > Checking Pull Request origin${BLANK}"
        echo -e "${CYAN}[ INFO ] > gh version.${BLANK}"
        gh --version

        echo -e "${YELLOW}[ EXECUTING ] > Cancelling workflow run ${{ inputs.run-id }}${BLANK}"
        PR=$(gh pr list --search "${{ inputs.commit }}" --state merged --json url --jq '.[0].url')

        if [ -n "$PR" ]
        then
          PR_NUMBER=$(echo "$PR" | awk -F '/' '{print $NF}')
          echo -e "${YELLOW}[ INFO ] > Commit ${PURPLE}${{ inputs.commit }}${YELLOW} is associated with PR number ${PURPLE}${PR_NUMBER}${BLANK}"
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_OUTPUT
        else
          echo -e "${YELLOW}[ INFO ] > Commit ${PURPLE}${{ inputs.commit }}${YELLOW} is not associated with a Pull Request${BLANK}"
        fi
      shell: bash
      env:
        RED: \033[1;31m
        GREEN: \033[1;32m
        YELLOW: \033[1;33m
        BLUE: \033[1;34m
        PURPLE: \033[1;35m
        CYAN: \033[1;36m
        BLANK: \033[0m
