---
name: Dynamic fetch component
description: Detecting component name by dynamic fetch
author: ixxeL
inputs:
  component-path-position:
    description: position of the component in the directory tree string
    required: false
    default: "1"
outputs:
  COMPONENT_NAME:
    description: Name of the component related to path change trigger
    value: ${{ steps.dynamic-path-fetch.outputs.COMPONENT_NAME }}

runs:
  using: composite
  steps:
    - id: dynamic-path-fetch
      run: |
        set +e
        echo -e "${BLUE}[ STEP - Component name fetching ] > Fetching component name${BLANK}"
        echo -e "${CYAN}[ INFO ] > gh version.${BLANK}"
        gh --version

        PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        echo -e "${CYAN}[ INFO ] > PR number is ${YELLOW}${PR_NUMBER}${BLANK}"
        # declare -A changed_files
        declare -a uniq_components
        changed_files=$(gh pr view ${PR_NUMBER} --json files --jq '.files.[].path')
        IFS=$'\n' read -rd '' -a files_array <<<"$changed_files"

        for file in "${files_array[@]}"
        do
          echo -e "${CYAN}[ INFO ] > Changed path is ${YELLOW}${file}${BLANK}"
          COMPONENT_NAME=$(echo ${file} | awk -F'/' -v nb="${{ inputs.component-path-position }}" '{print $nb}')
          if [[ "$COMPONENT_NAME" != ".github" ]]; then
            if [[ ! " ${uniq_components[*]} " =~ $COMPONENT_NAME ]]; then
              uniq_components+=("$COMPONENT_NAME")
            fi
          fi
        done

        if [[ ${#uniq_components[@]} -gt 0 ]]; then
          echo -e "${CYAN}[ INFO ] > Component name is ${YELLOW}${uniq_components[0]}${BLANK}"
          echo "COMPONENT_NAME=${uniq_components[0]}" >> $GITHUB_OUTPUT
          exit 0
        else
          echo -e "${RED}[ ERROR ] > Error, component not found${BLANK}"
          exit 1
        fi
      shell: bash
      env:
        RED: \033[1;31m
        GREEN: \033[1;32m
        YELLOW: \033[1;33m
        BLUE: \033[1;34m
        PURPLE: \033[1;35m
        CYAN: \033[1;36m
        BLANK: \033[0m
