---
name: GCloud gar-auth
description: Authenticating to gar
author: ixxeL
inputs:
  registry:
    required: true
    description: registry to auth to
outputs:
  IMG_DIGEST:
    description: Digest of the image associated with searched tag
    value: ${{ steps.get-img-info.outputs.CHART_NAME }}
  IMG_SHA:
    description: Commit SHA tag of the image associated with searched tag
    value: ${{ steps.get-img-info.outputs.CHART_VERSION }}

runs:
  using: composite
  steps:
    - id: gcloud-gar-auth
      run: |
        echo -e "${BLUE}[ STEP - GAR AUTH ] > GCloud GAR Authentication${BLANK}"
        echo -e "${CYAN}[ INFO ] > gcloud version.${BLANK}"
        gcloud --version

        echo -e "${YELLOW}[ EXECUTING ] > Authenticating to GAR ${{ inputs.registry }}${BLANK}"
        rm ~/.docker/config.json || true
        gcloud auth configure-docker ${{ inputs.registry }} --quiet

      shell: bash
      env:
        RED: \033[1;31m
        GREEN: \033[1;32m
        YELLOW: \033[1;33m
        BLUE: \033[1;34m
        PURPLE: \033[1;35m
        CYAN: \033[1;36m
        BLANK: \033[0m
