---
name: YARN run
description: Running script with yarn
author: ixxeL
inputs:
  script:
    description: Script to run with yarn
    required: false
    default: "build"
  workingdir:
    description: directory in which to find the Dockerfile
    required: false
    default: .

runs:
  using: composite
  steps:
    - id: yarn-run
      working-directory: ${{ inputs.workingdir }}
      run: |
        set +e
        echo -e "${BLUE}[ STEP - PNPM run ] > Running script with Yarn${BLANK}"
        echo -e "${CYAN}[ INFO ] > yarn version.${BLANK}"
        yarn --version

        echo -e "${YELLOW}[ EXECUTING ] > Executing script ${{ inputs.script }} with yarn${BLANK}"
        yarn ${{ inputs.script }}

        if [[ $? = 0 ]]
        then
          echo -e "${GREEN}[ SUCCESS ] > YARN ${{ inputs.script }} executed succesfully${BLANK}"
        else
          echo -e "${PURPLE}[ ERROR ] > YARN ${{ inputs.script }} failed !${BLANK}"
          exit 1
        fi
      shell: bash
      env:
        RED: \033[1;31m
        GREEN: \033[1;32m
        YELLOW: \033[1;33m
        BLUE: \033[1;34m
        PURPLE: \033[1;35m
        CYAN: \033[1;36m
        BLANK: \033[0m
