---
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks
  autofix_prs: true
  autoupdate_branch: ""
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: weekly
  skip: [action-validator]
  submodules: false
default_install_hook_types: [pre-commit, commit-msg]
default_stages: [commit, manual]
fail_fast: false
repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: check-docstring-first
  - repo: https://github.com/mpalmer/action-validator
    rev: v0.5.3
    hooks:
      - id: action-validator
        files: '.github/.*/.*\.ya?ml'
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.23.3
    hooks:
      - id: check-github-actions
      - id: check-github-workflows
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
