---
name: Helm docs
description: Generate doc for helm
author: ixxeL
inputs:
  prepare:
    description: Prepare the job when not running in adequate environment
    required: false
    default: "false"
  chart-search-root:
    description: directory in which to find the Helm chart
    required: false
    default: .
  values-file:
    description: name of the values.yaml file
    required: false
    default: values.yaml

runs:
  using: composite
  steps:
    - id: prepare
      if: ${{ inputs.prepare == 'true' }}
      shell: bash
      run: |
        echo -e "${YELLOW}[ EXECUTING ] > Installing dependencies${BLANK}"
        HELMDOC_VERSION=$(curl -sSfL "https://github.com/norwoodj/helm-docs/releases/latest" | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+' | sort | uniq | tail -1)
        HELMDOC_VER_LIGHT=$(echo "$HELMDOC_VERSION" | sed 's/v//g')
        curl -sSfL "https://github.com/norwoodj/helm-docs/releases/download/${HELMDOC_VERSION}/helm-docs_${HELMDOC_VER_LIGHT}_Linux_x86_64.tar.gz" | tar -xz
        chmod +x ./helm-docs
        sudo mv ./helm-docs /usr/local/bin/helm-docs
      env:
        RED: \033[1;31m
        GREEN: \033[1;32m
        YELLOW: \033[1;33m
        BLUE: \033[1;34m
        PURPLE: \033[1;35m
        CYAN: \033[1;36m
        BLANK: \033[0m
    - name: helm-docs
      id: helm-docs
      run: |
        set +e
        echo -e "${BLUE}[ STEP - Helm-chart doc ] > Generating doc for helm chart${BLANK}"
        echo -e "${CYAN}[ INFO ] > Helm-docs version.${BLANK}"
        helm-docs --version

        if [[ -f ${{ inputs.chart-search-root }}/Chart.yaml ]]
        then
          echo -e "${CYAN}[ INFO ] > Chart.yaml file detected. Here is the file${BLANK}"
          echo -e "${YELLOW}[ EXECUTING ] > Generating helm documentation${BLANK}"
          helm-docs --chart-search-root=${{ inputs.chart-search-root }} --values-file=${{ inputs.values-file }}
        else
          echo -e "${PURPLE}[ WARNING ] > Chart.yaml file NOT detected.${BLANK}"
          exit 1
        fi

        if [[ $? = 0 ]]
        then
          echo -e "${GREEN}[ CHECK SUCCESS ] > Helm doc generated without any error.${BLANK}"
        else
          echo -e "${PURPLE}[ CHECK ERROR ] > Helm doc generation failed.${BLANK}"
          exit 1
        fi
      shell: bash
      env:
        RED: \033[1;31m
        GREEN: \033[1;32m
        YELLOW: \033[1;33m
        BLUE: \033[1;34m
        PURPLE: \033[1;35m
        CYAN: \033[1;36m
        BLANK: \033[0m
