---
name: Gradlew
description: Execute gradlew
author: ixxeL
inputs:
  workingdir:
    description: Specifies the working directory for the action. Defaults to current directory.
    required: false
    default: .
  project-dir:
    description: Specifies the start directory for Gradle. Defaults to current directory.
    required: false
    default: .
  init-script:
    description: Specifies the Gradle init script location.
    required: false
    default: "./init.gradle"
  warning-mode:
    description: Specifies which mode of warnings to generate. Values are 'all' (default), 'fail', 'summary' or 'none'.
    required: false
    default: all
  cmd:
    description: Specifies the Gradle tasks to execute.
    required: true
  parameters:
    description: Specifies the project properties for the build script (e.g. -Pmyprop1=myvalue1 -Pmyprop2=myvalue2).
    required: false
    default: ""

runs:
  using: composite
  steps:
    - id: chmod-gradlew
      working-directory: ${{ inputs.workingdir }}
      name: Grant execute permission for gradlew
      run: |
        set +e
        if [[ -f "gradlew" ]]
        then
          echo -e "${CYAN}[ INFO] > gradlew binary detected in current directory ${{ inputs.workingdir }}. Granting execution permission.${BLANK}"
          chmod +x gradlew
        else
          echo -e "${CYAN}[ INFO] > gradlew binary not detected, skipping permission promotion.${BLANK}"
        fi
      shell: bash
      env:
        RED: \033[1;31m
        GREEN: \033[1;32m
        YELLOW: \033[1;33m
        BLUE: \033[1;34m
        PURPLE: \033[1;35m
        CYAN: \033[1;36m
        BLANK: \033[0m
    - id: gradlew
      name: Execute gradle command
      working-directory: ${{ inputs.workingdir }}
      run: |
        echo -e "${BLUE}[ STEP - Gradlew ] > Execute gradlew ${{ inputs.cmd }} ${{ inputs.parameters }}${BLANK}"
        if [[ -f "${{ inputs.init-script }}" ]]
        then
          ./gradlew -p ${{ inputs.project-dir }} --init-script ${{ inputs.init-script }} --warning-mode ${{ inputs.warning-mode }} ${{ inputs.cmd }} ${{ inputs.parameters }}
        else
          ./gradlew -p ${{ inputs.project-dir }} --warning-mode ${{ inputs.warning-mode }} ${{ inputs.cmd }} ${{ inputs.parameters }}
        fi
      shell: bash
      env:
        RED: \033[1;31m
        GREEN: \033[1;32m
        YELLOW: \033[1;33m
        BLUE: \033[1;34m
        PURPLE: \033[1;35m
        CYAN: \033[1;36m
        BLANK: \033[0m
