---
name: Gradlew
description: Execute gradlew
author: ixxeL
inputs:
  workingdir:
    description: directory in which to find the Dockerfile
    required: false
    default: .
  init-script:
    description: gradle init script
    required: false
    default: "./init.gradle"
  warning-mode:
    description: warning mode
    required: false
    default: all
  cmd:
    description: command to execute
    required: true

runs:
  using: composite
  steps:
    - id: gradlew
      working-directory: ${{ inputs.workingdir }}
      run: |
        set +e
        echo -e "${BLUE}[ STEP - Gradlew ] > Execute gradlew ${{ inputs.cmd }}${BLANK}"
        ./gradlew -p . --init-script ${{ inputs.init-script }} --warning-mode ${{ inputs.warning-mode }} ${{ inputs.cmd }}
      shell: bash
      env:
        RED: \033[1;31m
        GREEN: \033[1;32m
        YELLOW: \033[1;33m
        BLUE: \033[1;34m
        PURPLE: \033[1;35m
        CYAN: \033[1;36m
        BLANK: \033[0m
