---
name: Git tag delete
description: Deleting tag git repo
author: ixxeL
inputs:
  tag:
    required: true
    description: tag to delete
  git-workdir:
    required: false
    default: .
    description: working directory for git

runs:
  using: composite
  steps:
    - id: git-tag-delete
      run: |
        set +e
        echo -e "${BLUE}[ STEP - DELETE GIT TAG ] > Deleting git tag on origin${BLANK}"
        echo -e "${CYAN}[ INFO ] > Git version.${BLANK}"
        git version

        echo -e "${YELLOW}[ EXECUTING ] > Showing repo information.${BLANK}"
        echo -e "${CYAN}[ INFO ] > git branch.${BLANK}"
        git -C ${{ inputs.git-workdir }} branch
        echo -e "${CYAN}[ INFO ] > git origin.${BLANK}"
        git -C ${{ inputs.git-workdir }} remote show origin

        echo -e "${CYAN}[ INFO ] > git remote tag${BLANK}"
        git ls-remote --tags origin
        if [[ $(git ls-remote --tags origin | awk -F' ' '{print $NF}' | awk -F/ '{print $NF}' | grep -Eo "^${{ inputs.tag }}$") ]]; then
          echo -e "${YELLOW}[ EXECUTING ] > Deleting tag ${{ inputs.tag }}${BLANK}"
          git -C ${{ inputs.git-workdir }} tag -d ${{ inputs.tag }}
          git -C ${{ inputs.git-workdir }} push --delete origin ${{ inputs.tag }}
        else
          echo -e "${CYAN}[ INFO ] > Tag is not present. No need to delete${BLANK}"
        fi

      shell: bash
      env:
        RED: \033[1;31m
        GREEN: \033[1;32m
        YELLOW: \033[1;33m
        BLUE: \033[1;34m
        PURPLE: \033[1;35m
        CYAN: \033[1;36m
        BLANK: \033[0m
