---
name: Envsubst
description: Substituting variables
author: ixxeL
inputs:
  prepare:
    description: Prepare the job when not running in adequate environment
    required: false
    default: "true"
  file-input:
    description: name of the file to input
    required: true
  file-output:
    description: name of the file to output
    required: true

runs:
  using: composite
  steps:
    - id: prepare
      if: ${{ inputs.prepare == 'true' }}
      run: |
        set -e
        echo -e "${YELLOW}[ EXECUTING ] > Installing envsubst${BLANK}"
        sudo apt install gettext-base
      shell: bash
      env:
        RED: \033[1;31m
        GREEN: \033[1;32m
        YELLOW: \033[1;33m
        BLUE: \033[1;34m
        PURPLE: \033[1;35m
        CYAN: \033[1;36m
        BLANK: \033[0m
    - id: envsubst
      run: |
        set -e
        echo -e "${BLUE}[ STEP - Envsubst ] > Substituting env vars${BLANK}"
        echo -e "${CYAN}[ INFO ] > substituting file ${{ inputs.file-input }}${BLANK}"
        envsubst < ${{ inputs.file-input }} > ${{ inputs.file-input }}.tmp
        mv ${{ inputs.file-input }}.tmp ${{ inputs.file-output }}
      shell: bash
      env:
        RED: \033[1;31m
        GREEN: \033[1;32m
        YELLOW: \033[1;33m
        BLUE: \033[1;34m
        PURPLE: \033[1;35m
        CYAN: \033[1;36m
        BLANK: \033[0m
