---
name: Kyverno apply
description: Checking manifest compliance with Kyverno
author: ixxeL
inputs:
  prepare:
    description: Prepare the job when not running in adequate environment
    required: false
    default: "true"
  workingdir:
    description: directory in which to find the Dockerfile
    required: false
    default: .
  policies-dir:
    description: where to find the kyverno policies
    required: false
  manifest-dir:
    description: where to find the manifests to check
    required: false
  detailed-results:
    description: display detailed results
    required: false
    default: "false"
  audit-warn:
    description: set results as audit for audit rules
    required: false
    default: "true"
  warn-exit-code:
    description: set exit code for warnings
    required: false
    default: "0"
runs:
  using: composite
  steps:
    - id: kyverno-install
      uses: kyverno/action-install-cli@v0.2.0
      with:
        release: "v1.11.1"
    - id: kyverno-apply
      run: |
        set +e
        echo -e "${BLUE}[ STEP - Kyverno ] > Kyverno analyzis${BLANK}"
        echo -e "${CYAN}[ INFO ] > Kyverno version.${BLANK}"
        kyverno version
        echo -e "${YELLOW}[ EXECUTING ] > Kyverno apply with policies ${{ inputs.policies-dir }} on manifests ${{ inputs.manifest-dir }}${BLANK}"

        if [[ ( -d  ${{ inputs.policies-dir }} || -f  ${{ inputs.policies-dir }}) && ( -d  ${{ inputs.manifest-dir }} || -f  ${{ inputs.manifest-dir }}) ]]
        then
        script -q -e -c "kyverno apply ${{ inputs.policies-dir }} --resource=${{ inputs.manifest-dir }} \
                                 --table \
                                 --detailed-results=${{ inputs.detailed-results }} \
                                 --audit-warn=${{ inputs.audit-warn }} \
                                 --warn-exit-code=${{ inputs.warn-exit-code }}"
        else
          echo -e "${RED}[ CHECK ERROR ] > Either ${{ inputs.policies-dir }} or ${{ inputs.manifest-dir }} doesnt exists${BLANK}"
          exit 1
        fi
        if [[ $? = 0 ]]
        then
          echo -e "${GREEN}[ CHECK SUCCESS ] > Kyverno check succeeded without any error.${BLANK}"
          exit 0
        else
          echo -e "${PURPLE}[ CHECK ERROR ] > Kyverno check didn't succeed, please review your manifest(s)${BLANK}"
          exit 1
        fi
      shell: bash
      env:
        RED: \033[1;31m
        GREEN: \033[1;32m
        YELLOW: \033[1;33m
        BLUE: \033[1;34m
        PURPLE: \033[1;35m
        CYAN: \033[1;36m
        BLANK: \033[0m
