---
name: Get PR modified files
description: Getr modified files from a Pull Request
author: ixxeL
outputs:
  MODIFIED_FILES:
    description: The helmrelease name
    value: ${{ steps.get-pr-modified-files.outputs.MODIFIED_FILES }}

runs:
  using: composite
  steps:
    - id: get-pr-modified-files
      run: |
        set +e
        echo -e "${BLUE}[ STEP - GET PR MODIFIED FILES ] > Fetching Pull Request modified files${BLANK}"
        echo -e "${CYAN}[ INFO ] > gh version.${BLANK}"
        gh --version

        PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        echo -e "${CYAN}[ INFO ] > PR number is ${YELLOW}${PR_NUMBER}${BLANK}"
        changed_files=$(gh pr view ${PR_NUMBER} --json files --jq '.files.[].path')
        IFS=$'\n' read -rd '' -a files_array <<<"$changed_files"
        for file in "${files_array[@]}"
        do
          echo -e "${CYAN}[ INFO ] > Changed path is ${YELLOW}${file}${BLANK}"
        done
        echo "MODIFIED_FILES=$files_array" >> $GITHUB_OUTPUT
      shell: bash
      env:
        RED: \033[1;31m
        GREEN: \033[1;32m
        YELLOW: \033[1;33m
        BLUE: \033[1;34m
        PURPLE: \033[1;35m
        CYAN: \033[1;36m
        BLANK: \033[0m
