---
name: Change action ref
description: Changing action reference
author: ixxeL
inputs:
  workflows-directory:
    description: directory in which to find workflows
    required: false
  actions-source:
    description: origin of actions
    required: false
  new-ref:
    description: current version to update
    required: true
outputs:
  VERSION:
    description: chart version
    value: ${{ steps.bump-version.outputs.VERSION }}

runs:
  using: composite
  steps:
    - id: change-action-ref
      run: |
        for file in ${{ inputs.workflows-directory }}
        do
          for line in $(yq e '.jobs[].steps[].uses | select(.) | select(.=="'"${{ inputs.actions-source }}"'*@*")' $file)
          do
            ACTION=$(echo "$line" | awk -F@ '{print $1}' | awk -F/ '{print $NF}')
            REF=$(echo "$line" | awk -F@ '{print $NF}')
            if [[ "$REF" != "${{ inputs.new-ref }}" ]]; then
              echo -e "${CYAN}[ INFO ] > File ${YELLOW}$file${CYAN} and action ${PURPLE}$ACTION${CYAN} is currently set to ref ${RED}$REF${CYAN} and will be changed to ${GREEN}${{ inputs.new-ref }}${BLANK}"
              yq e -i '.jobs[].steps[] |= select(.uses).uses |= select(.=="'"$line"'") |= sub("'"@$REF"'", "'"@${{ inputs.new-ref }}"'")' $file
            else
              echo -e "${PURPLE}[ CANCEL ] > File ${YELLOW}$file${PURPLE} and action ${RED}$ACTION${PURPLE} is already set to ${RED}${{ inputs.new-ref }}${PURPLE} ref${BLANK}"
            fi
          done

          for key in $(yq e '.jobs | select(.) | keys' $file)
          do
            for line in $(yq e '.jobs."'"$key"'".uses | select(.) | select(.=="'"${{ inputs.actions-source }}"'*@*")' $file)
            do
              ACTION=$(echo "$line" | awk -F@ '{print $1}' | awk -F/ '{print $NF}')
              REF=$(echo "$line" | awk -F@ '{print $NF}')
              if [[ "$REF" != "${{ inputs.new-ref }}" ]]; then
                echo -e "${CYAN}[ INFO ] > File ${YELLOW}$file${CYAN} and ${BLUE}workflow${CYAN} ${PURPLE}$ACTION${CYAN} is currently set to ref ${RED}$REF${CYAN} and will be changed to ${GREEN}${{ inputs.new-ref }}${BLANK}"
                yq e -i '.jobs."'"$key"'" |= select(.uses).uses |= select(.=="'"$line"'") |= sub("'"@$REF"'", "'"@${{ inputs.new-ref }}"'")' $file
              else
                echo -e "${PURPLE}[ CANCEL ] > File ${YELLOW}$file${PURPLE} and ${BLUE}workflow${CYAN} ${RED}$ACTION${PURPLE} is already set to ${RED}${{ inputs.new-ref }}${PURPLE} ref${BLANK}"
              fi
            done
          done
        done
      shell: bash
      env:
        RED: \033[1;31m
        GREEN: \033[1;32m
        YELLOW: \033[1;33m
        BLUE: \033[1;34m
        PURPLE: \033[1;35m
        CYAN: \033[1;36m
        BLANK: \033[0m
