---
name: Regex check
description: Check input against REGEX
author: ixxeL
inputs:
  string-to-evaluate:
    required: true
    description: string to evaluate against regex
  regex:
    required: true
    description: second file to compare
runs:
  using: composite
  steps:
    - id: regex-check
      run: |
        set +e
        echo -e "${BLUE}[ STEP - REGEX CHECK ] > Checking input against REGEX${BLANK}"
        REGEX="${{ inputs.regex }}"
        echo -e "${YELLOW}[ EXECUTING ] > Processing regex checking for ${PURPLE}${{ inputs.string-to-evaluate }}${YELLOW} against ${PURPLE}${{ inputs.regex }} ${BLANK}"
        if [[ "${{ inputs.string-to-evaluate }}" =~ ${REGEX} ]]
        then
          echo -e "${GREEN}[ SUCCESS ] > Regex check succeeded${BLANK}"
          exit 0
        else
          echo -e "${RED}[ FAIL ] > Regex check failed !${BLANK}"
          exit 1
        fi
      shell: bash
      env:
        RED: \033[1;31m
        GREEN: \033[1;32m
        YELLOW: \033[1;33m
        BLUE: \033[1;34m
        PURPLE: \033[1;35m
        CYAN: \033[1;36m
        BLANK: \033[0m
