---
name: Dyff
description: Using dyff to diff files
author: ixxeL
inputs:
  first-file:
    required: true
    description: first file to compare
  second-file:
    required: true
    description: second file to compare
  exclude-regexp:
    required: false
    default: "spec.template.metadata.annotations.checksum"
    description: regexp to exclude from comparison
  prepare:
    description: Prepare the job when not running in adequate environment
    required: false
    default: "true"
outputs:
  DYFF_RESULT:
    description: output result of dyff
    value: ${{ steps.dyff.outputs.DYFF_RESULT }}

runs:
  using: composite
  steps:
    - id: prepare
      if: ${{ inputs.prepare == 'true' }}
      run: |
        set +e
        dyff version
        if [[ $? = 0 ]]
        then
          echo -e "${CYAN}[ INFO ] > Dyff already installed${BLANK}"
        else
          echo -e "${YELLOW}[ EXECUTING ] > Installing Dyff${BLANK}"
          curl --silent --location https://git.io/JYfAY | sudo bash
        fi
      shell: bash
      env:
        RED: \033[1;31m
        GREEN: \033[1;32m
        YELLOW: \033[1;33m
        BLUE: \033[1;34m
        PURPLE: \033[1;35m
        CYAN: \033[1;36m
        BLANK: \033[0m
    - id: dyff
      run: |
        set +e
        echo -e "${BLUE}[ STEP - DYFF ] > Diffing files with Dyff${BLANK}"
        RESULT=$(dyff between --color on \
                     --output human \
                     --truecolor on \
                     --exclude-regexp ${{ inputs.exclude-regexp }} \
                     ${{ inputs.first-file }} ${{ inputs.second-file }})
        echo "${RESULT}"
        CLEANED_RESULT=$(echo "${RESULT}" | sed -r "s/\x1B\[[0-9;]+[mGKFHmsu]//g")
        {
          echo 'DYFF_RESULT<<EOF'
          echo "${CLEANED_RESULT}"
          echo EOF
        } >> $GITHUB_OUTPUT
        exit 0
      shell: bash
      env:
        RED: \033[1;31m
        GREEN: \033[1;32m
        YELLOW: \033[1;33m
        BLUE: \033[1;34m
        PURPLE: \033[1;35m
        CYAN: \033[1;36m
        BLANK: \033[0m
