---
name: Changelog generate
description: Generating CHANGELOG.md
author: ixxeL
inputs:
  workingdir:
    description: directory in which to find the Dockerfile
    required: false
    default: .
  install:
    description: Prepare the job when not running in adequate environment
    required: false
    default: "true"
  prepare:
    description: Prepare the job when not running in adequate environment
    required: false
    default: "true"
  lower-tag:
    description: Name of the release
    required: false
    default: New release
  upper-tag:
    description: Name of the release
    required: false
    default: New release
  config-file:
    description: Name of the config changelog
    required: false
    default: ".config-changelog.yml"

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      if: ${{ inputs.install == 'true' }}
      with:
        python-version: "3.12"
    - id: prepare
      if: ${{ inputs.prepare == 'true' }}
      shell: bash
      run: |
        set +e
        if command -v pip &> /dev/null; then
          pip install pyyaml
        elif command -v pip3 &> /dev/null; then
          pip3 install pyyaml
        else
          echo "Error pip/pip3 not found"
          exit 1
        fi
      env:
        RED: \033[1;31m
        GREEN: \033[1;32m
        YELLOW: \033[1;33m
        BLUE: \033[1;34m
        PURPLE: \033[1;35m
        CYAN: \033[1;36m
        BLANK: \033[0m
    - id: generate-changelog
      working-directory: ${{ github.workspace }}
      run: |
        import subprocess
        import yaml
        import re
        from typing import List, Dict, Optional

        def run_command(command: List[str]) -> str:
          result = subprocess.run(command, stdout=subprocess.PIPE, text=True)
          return result.stdout.strip()


        def run_command_list(command: List[str]) -> List[str]:
          result = subprocess.run(command, stdout=subprocess.PIPE, text=True)
          return result.stdout.strip().split('\n')


        def classify_commits(commits: List[str], groups: List[Dict[str, Optional[str]]]) -> Dict[str, List[str]]:
          classified_commits = {group['title']: [] for group in groups}

          for commit in commits:
              for group in groups:
                  regexp = group['regexp']
                  if commit and commit.strip() and bool(re.match(regexp, commit)):
                      print(f"found commit {commit} in group {group['title']}")
                      classified_commits[group['title']].append(commit)

          return classified_commits

        def replace_pull_requests(message, repo_url):
          def replace(match):
              pull_number = match.group(1)
              return f'in ({repo_url}/pull/{pull_number})'

          return re.sub(r'\(#(\d+)\)$', replace, message)

        def generate_markdown(classified_commits, lower_tag, upper_tag, repo_url):
            markdown = "## Changelog\n"
            pattern = '^([a-f0-9]+) (.+) @(.+)$'

            for title, commits in classified_commits.items():
                if commits:
                    markdown += f"### {title}\n"
                    for commit in commits:
                        match = re.match(pattern, commit)
                        if match:
                            sha, rest, author = match.groups()
                            rest = replace_pull_requests(rest, repo_url)
                            markdown += f"* {sha}: {rest} by (@{author})\n"
                    markdown += "\n"

            markdown += f"**Full Changelog**: {repo_url}/compare/{lower_tag}...{upper_tag}"
            return markdown

        def main():
          lower_tag = "${{ inputs.lower-tag }}"
          upper_tag = "${{ inputs.upper-tag }}"
          repo_url = "${{ github.server_url }}/${{ github.repository }}"

          config_file = "${{ inputs.config-file }}"

          commits = run_command_list(['git', 'log', f'{lower_tag}..{upper_tag}', '--pretty=format:%H %s @%an'])

          with open(config_file, 'r') as config_file:
              config = yaml.load(config_file, Loader=yaml.FullLoader)

          classified_commits = classify_commits(commits, config['groups'])

          final_markdown = generate_markdown(classified_commits, lower_tag, upper_tag, repo_url)

          print(final_markdown)

          with open('CHANGELOG.md', 'w') as file:
              file.write(final_markdown)

        if __name__ == "__main__":
            main()
      shell: python
      env:
        RED: \033[1;31m
        GREEN: \033[1;32m
        YELLOW: \033[1;33m
        BLUE: \033[1;34m
        PURPLE: \033[1;35m
        CYAN: \033[1;36m
        BLANK: \033[0m
