---
name: Git config
description: Configuring git
author: ixxeL
inputs:
  git-workdir:
    required: false
    default: .
    description: working directory
  tls-verify:
    required: false
    default: "true"
    description: tls verification
  git-email:
    required: false
    default: ${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com
    description: default git email
  git-username:
    required: false
    default: ${{ github.actor }}
    description: default git email

runs:
  using: composite
  steps:
    - id: git-config
      run: |
        echo -e "${BLUE}[ STEP - GIT CONFIG ] > Configure git${BLANK}"
        echo -e "${CYAN}[ INFO ] > Git version.${BLANK}"
        git version

        echo -e "${YELLOW}[ EXECUTING ] > setting up git config to mail ${{ inputs.git-email }} and username ${{ inputs.git-username }}.${BLANK}"
        git config --global --add safe.directory "$(realpath "${{ inputs.git-workdir }}")"
        git config --global user.email "${{ inputs.git-email }}"
        git config --global user.name "${{ inputs.git-username }}"
        git config --global http.sslVerify ${{ inputs.tls-verify }}
        git config --list
      shell: bash
      env:
        RED: \033[1;31m
        GREEN: \033[1;32m
        YELLOW: \033[1;33m
        BLUE: \033[1;34m
        PURPLE: \033[1;35m
        CYAN: \033[1;36m
        BLANK: \033[0m
