---
name: Helm datree
description: Datree scan Helm chart with helm datree plugin
author: ixxeL
inputs:
  workingdir:
    description: directory in which to find the Dockerfile
    required: false
    default: .
  datree-offline:
    description: using offline feature of datree
    required: false
    default: "false"
  kube-schema-version:
    description: kubernetes apiversion
    required: false
    default: 1.25.0

runs:
  using: composite
  steps:
    - id: helm-datree
      run: |
        set +e
        echo -e "${BLUE}[ STEP - Helm-chart unittest ] > Datree scan Helm chart.${BLANK}"
        echo -e "${CYAN}[ INFO ] > Helm version.${BLANK}"
        helm version --short
        echo -e "${CYAN}[ INFO ] > Displaying plugins list.${BLANK}"
        helm plugin list
        echo -e "${CYAN}[ INFO ] > Helm datree version.${BLANK}"
        helm datree version

        if [[ ${{ inputs.datree-offline }} = true ]]
        then
          echo -e "${CYAN}[ INFO ] > Using helm datree offline${BLANK}"
          helm datree config set offline local
        fi

        echo -e "${YELLOW}[ EXECUTING ] > Scaning helm chart ${{ inputs.workingdir }}.${BLANK}"
        if [[ -d ${{ inputs.workingdir }} ]]
        then
          echo -e "${GREEN}[ CHECK SUCCESS ] > Directory exists, proceeding scaning.${BLANK}"
        else
          echo -e "${RED}[ CHECK ERROR ] > Directory doesn't exist, canceling scaning.${BLANK}"
          exit 1
        fi
        echo -e "${CYAN}[ INFO ] > Scaning against Kube schema version ${{ inputs.kube-schema-version }}${BLANK}"
        script -q -e -c "helm datree test ${{ inputs.workingdir }} --no-record --ignore-missing-schemas --schema-version ${{ inputs.kube-schema-version }}"

        if [[ $? = 0 ]]
        then
          echo -e "${GREEN}[ SUCCESS ] > Helm datree scan succeeded without any error.${BLANK}"
        else
          echo -e "${RED}[ ERROR ] > Helm datree scan didn't succeed !${BLANK}"
          exit 1
        fi
      shell: bash
      env:
        RED: \033[1;31m
        GREEN: \033[1;32m
        YELLOW: \033[1;33m
        BLUE: \033[1;34m
        PURPLE: \033[1;35m
        CYAN: \033[1;36m
        BLANK: \033[0m
        HELM_PLUGINS: /root/.local/share/helm/plugins
