---
name: Helm lint
description: Lint Helm chart with helm CLI
author: ixxeL
inputs:
  workingdir:
    description: directory in which to find the Dockerfile
    required: false
    default: .
  strict:
    description: use strict mode
    required: false
    default: "true"
  values-file:
    description: name of the values.yaml file
    required: false
    default: values.yaml
outputs:
  CHART_NAME:
    description: chart name
    value: ${{ steps.helm-lint.outputs.CHART_NAME }}
  CHART_VERSION:
    description: chart version
    value: ${{ steps.helm-lint.outputs.CHART_VERSION }}
  CHART_APP_VERSION:
    description: chart appVersion
    value: ${{ steps.helm-lint.outputs.CHART_APP_VERSION }}

runs:
  using: composite
  steps:
    - name: helm-lint
      id: helm-lint
      run: |
        set +e
        echo -e "${BLUE}[ STEP - Helm-chart linting ] > Linting Helm chart.${BLANK}"
        echo -e "${CYAN}[ INFO ] > Helm version.${BLANK}"
        helm version --short

        echo -e "${YELLOW}[ EXECUTING ] > Checking helm chart ${{ inputs.workingdir }}.${BLANK}"
        if [[ -d ${{ inputs.workingdir }} ]]
        then
          echo -e "${GREEN}[ CHECK SUCCESS ] > Directory exists, proceeding linting.${BLANK}"
        else
          echo -e "${RED}[ CHECK ERROR ] > Directory doesn't exist, canceling linting.${BLANK}"
          exit 1
        fi
        if [[ -f ${{ inputs.workingdir }}/Chart.yaml ]]
        then
          echo -e "${CYAN}[ INFO ] > Chart.yaml file detected. Here is the file${BLANK}"
          yq e ${{ inputs.workingdir }}/Chart.yaml -C
          CHART_NAME=$(yq e '.name' ${{ inputs.workingdir }}/Chart.yaml)
          CHART_VERSION=$(yq e '.version' ${{ inputs.workingdir }}/Chart.yaml)
          CHART_APP_VERSION=$(yq e '.appVersion' ${{ inputs.workingdir }}/Chart.yaml)
          echo -e "${CYAN}[ INFO ] > The chart [[ ${YELLOW}${CHART_NAME}${CYAN} ]] has version --> [[ ${YELLOW}${CHART_VERSION}${CYAN} ]] and appVersion --> [[ ${YELLOW}${CHART_APP_VERSION}${CYAN} ]]${BLANK}"
        else
          echo -e "${PURPLE}[ WARNING ] > Chart.yaml file NOT detected.${BLANK}"
          exit 1
        fi
        echo -e "${YELLOW}[ EXECUTING ] > Checking Helm linting on chart ${CHART_NAME}.${BLANK}"
        helm lint ${{ inputs.workingdir }} --with-subcharts \
                                --values=${{ inputs.workingdir }}/${{ inputs.values-file }} \
                                --strict=${{ inputs.strict }}
        if [[ $? = 0 ]]
        then
          echo -e "${GREEN}[ CHECK SUCCESS ] > Helm Lint succeeded without any error.${BLANK}"
          echo "CHART_NAME=$CHART_NAME" >> $GITHUB_OUTPUT
          echo "CHART_VERSION=$CHART_VERSION" >> $GITHUB_OUTPUT
          echo "CHART_APP_VERSION=$CHART_APP_VERSION" >> $GITHUB_OUTPUT
        else
          echo -e "${PURPLE}[ CHECK ERROR ] > Helm Lint didn't succeed, please review your helm chart.${BLANK}"
          exit 1
        fi
      shell: bash
      env:
        RED: \033[1;31m
        GREEN: \033[1;32m
        YELLOW: \033[1;33m
        BLUE: \033[1;34m
        PURPLE: \033[1;35m
        CYAN: \033[1;36m
        BLANK: \033[0m
