---
name: Define tag
description: Define tag for Docker image and git repository
author: ixxeL
inputs:
  current-branch:
    required: false
    default: "true"
    description: current git branch
  repo-style:
    required: false
    default: poly
    description: repository style (poly or mono)
outputs:
  TARGET_TAG:
    description: tag defined
    value: ${{ steps.define-tag.outputs.TARGET_TAG }}

runs:
  using: composite
  steps:
    - id: define-tag
      run: |
        set +e
        echo -e "${BLUE}[ STEP - DEFINE TAG ] > Defining target tag${BLANK}"
        if [[ "${{ inputs.repo-style }}" == 'poly' ]]; then
          echo -e "${CYAN}[ INFO ] > Poly-repo style used, using classic pattern <branch>-<run-number> --> ${PURPLE}${{ inputs.current-branch }}-${{ github.run_number }}${BLANK}"
          echo "TARGET_TAG=${{ inputs.current-branch }}-${{ github.run_number }}" >> "$GITHUB_OUTPUT"
          TARGET_TAG="${{ inputs.current-branch }}-${{ github.run_number }}"
          echo -e "${YELLOW}[ INFO ] > Target tag is ${PURPLE}${TARGET_TAG}${BLANK}"
        elif [[ "${{ inputs.repo-style }}" == 'mono' ]]; then
          echo -e "${CYAN}[ INFO ] > Mono-repo style used, using derived pattern <branch>-<short-sha>-<run-number> --> ${PURPLE}${{ inputs.current-branch }}-${GITHUB_SHA:0:7}-${{ github.run_number }}${BLANK}"
          echo "TARGET_TAG=${{ inputs.current-branch }}-${GITHUB_SHA:0:7}-${{ github.run_number }}" >> "$GITHUB_OUTPUT"
          TARGET_TAG="${{ inputs.current-branch }}-${GITHUB_SHA:0:7}-${{ github.run_number }}"
          echo -e "${YELLOW}[ INFO ] > Target tag is ${PURPLE}${TARGET_TAG}${BLANK}"
        else
          echo -e "${RED}[ ERROR ] > Repo style ${{ inputs.repo-style }} is not correct${BLANK}"
          exit 1
        fi
      shell: bash
      env:
        RED: \033[1;31m
        GREEN: \033[1;32m
        YELLOW: \033[1;33m
        BLUE: \033[1;34m
        PURPLE: \033[1;35m
        CYAN: \033[1;36m
        BLANK: \033[0m
