---
name: GCloud add-tag
description: Add tag to docker image in GCloud GAR
author: ixxeL
inputs:
  image-fullname:
    required: true
    description: name of the docker image
  src-image-tag:
    required: true
    description: name of the source docker image
  dst-image-tag:
    required: true
    description: name of the destination docker image

runs:
  using: composite
  steps:
    - id: gcloud-add-tag
      run: |
        echo -e "${BLUE}[ STEP - ADD TAG ] > Add tag to image in GAR${BLANK}"
        echo -e "${CYAN}[ INFO ] > gcloud version.${BLANK}"
        gcloud --version

        echo -e "${YELLOW}[ EXECUTING ] > Adding tag ${{ inputs.dst-image-tag }} to image ${{ inputs.image-fullname }}:${{ inputs.src-image-tag }}${BLANK}"
        gcloud container images add-tag ${{ inputs.image-fullname }}:${{ inputs.src-image-tag }} ${{ inputs.image-fullname }}:${{ inputs.dst-image-tag }} --quiet
        gcloud container images list-tags ${{ inputs.image-fullname }} --filter="tags=${{ inputs.src-image-tag }}" --format=json | jq -C '.[].tags[]'

      shell: bash
      env:
        RED: \033[1;31m
        GREEN: \033[1;32m
        YELLOW: \033[1;33m
        BLUE: \033[1;34m
        PURPLE: \033[1;35m
        CYAN: \033[1;36m
        BLANK: \033[0m
