---
name: SVU
description: Semantic Versioning Utils
author: ixxeL
inputs:
  prepare:
    default: "true"
    required: false
    description: prepare env
  workingdir:
    required: false
    description: working directory
    default: .
  component:
    required: false
    default: ""
    description: note file or stdin
  prerelease:
    required: false
    default: "false"
    description: use prerelease
  prerelease-pattern:
    required: false
    default: "rc"
    description: use prerelease
outputs:
  LAST_TAG:
    description: last git tag
    value: ${{ steps.svu.outputs.LAST_TAG }}
  VERSION:
    description: next git tag
    value: ${{ steps.svu.outputs.VERSION }}

runs:
  using: composite
  steps:
    - id: prepare
      if: ${{ inputs.prepare == 'true' }}
      shell: bash
      run: |
        set +e
        mkdir -p target_dir
        wget -q https://github.com/caarlos0/svu/releases/download/v1.12.0/svu_1.12.0_linux_amd64.tar.gz -P target_dir
        cd target_dir || exit
        tar -xzvf svu_1.12.0_linux_amd64.tar.gz
        chmod +x svu
        mv svu /usr/local/bin/
        cd .. || exit
        rm -rf target_dir
      env:
        RED: \033[1;31m
        GREEN: \033[1;32m
        YELLOW: \033[1;33m
        BLUE: \033[1;34m
        PURPLE: \033[1;35m
        CYAN: \033[1;36m
        BLANK: \033[0m
    - id: svu
      run: |
        set +e
        echo -e "${BLUE}[ STEP - SVU ] > Semantic Versioning Utils${BLANK}"
        echo -e "${CYAN}[ INFO ] > svu version.${BLANK}"
        svu --version

        if [ -n "${{ inputs.component }}" ]
        then
          COMPONENT="${{ inputs.component }}-"
        fi
        if [ "${{ inputs.prerelease }}" == "true" ]
        then
          echo -e "${CYAN}[ INFO ] > Prerelease mode activated${BLANK}"
          PRERELEASE_PATTERN="-${{ inputs.prerelease-pattern }}*"
        else
          echo -e "${CYAN}[ INFO ] > Final Release mode activated${BLANK}"
        fi

        echo -e "${YELLOW}[ EXECUTING ] > Calculating current and next tag${BLANK}"
        LAST_TAG=$(svu current --prefix="${COMPONENT}v" --pattern="${COMPONENT}v[0-9]*.[0-9]*.[0-9]*${PRERELEASE_PATTERN}" --directory=${{ inputs.workingdir }})
        if [ $? -ne 0 ]
        then
          LAST_TAG=""
          if [ "${{ inputs.prerelease }}" == "true" ]
          then
            LAST_TAG=$(svu current --prefix="${COMPONENT}v" --pattern="${COMPONENT}v[0-9]*.[0-9]*.[0-9]*" --directory=${{ inputs.workingdir }})
            if [ $? -ne 0 ]
            then
              LAST_TAG=""
              VERSION="${COMPONENT}v0.1.0-${{ inputs.prerelease-pattern }}.0"
            else
              VERSION=$(svu prerelease --pre-release=${{ inputs.prerelease-pattern }} --prefix="${COMPONENT}v" --pattern="${COMPONENT}v[0-9]*.[0-9]*.[0-9]*" --directory=${{ inputs.workingdir }})
              if [ "$(echo "$VERSION" | awk -F "$PRERELEASE_PATTERN" '{print $1}')" == "$LAST_TAG" ]
              then
                echo -e "${RED}[ ERROR ] > Cancel to avoid irrelevant RC ${YELLOW}($VERSION)${RED} and GA ${YELLOW}($LAST_TAG)${RED} version${BLANK}"
                echo -e "${RED}[ ERROR ] > You are trying to release a RC version not aligned with current GA version. Check that your commit messages trigger a bump (fix, feat) or that you are not on the same commit-sha.${BLANK}"
                exit 1
              fi
            fi
          else
            VERSION="${COMPONENT}v0.1.0"
          fi
        else
          if [ "${{ inputs.prerelease }}" == "true" ]
          then
            VERSION=$(svu prerelease --pre-release=${{ inputs.prerelease-pattern }} --prefix="${COMPONENT}v" --pattern="${COMPONENT}v[0-9]*.[0-9]*.[0-9]*" --directory=${{ inputs.workingdir }})
          else
            VERSION=$(svu next --prefix="${COMPONENT}v" --pattern="${COMPONENT}v[0-9]*.[0-9]*.[0-9]*" --directory=${{ inputs.workingdir }})
          fi
        fi
        if [ "${LAST_TAG}" == "${VERSION}" ]
        then
          echo -e "${RED}[ ERROR ] > Current tag ${YELLOW}${LAST_TAG}${RED} is same as new tag ${YELLOW}${VERSION}${BLANK}"
          echo -e "${RED}[ ERROR ] > You are trying to release a version already existing. Check that your commit messages trigger a bump (fix, feat) or that you are not on the same commit-sha.${BLANK}"
          exit 1
        fi
        echo -e "${CYAN}[ INFO ] > Current tag is ${PURPLE}${LAST_TAG}${BLANK}"
        echo -e "${CYAN}[ INFO ] > New tag is ${PURPLE}${VERSION}${BLANK}"
        echo "LAST_TAG=$LAST_TAG" >> $GITHUB_OUTPUT
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
      shell: bash
      env:
        RED: \033[1;31m
        GREEN: \033[1;32m
        YELLOW: \033[1;33m
        BLUE: \033[1;34m
        PURPLE: \033[1;35m
        CYAN: \033[1;36m
        BLANK: \033[0m
