---
name: PNPM setup
description: setup node js and pnpm
author: ixxeL
inputs:
  node-version:
    description: version of node to install
    required: false
    default: "18"
  pnpm-version:
    description: version of pnpm to install
    required: false
    default: "8"

runs:
  using: composite
  steps:
    - name: Setup Node.js
      id: setup-node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
    - name: Setup pnpm
      id: setup-pnpm
      uses: pnpm/action-setup@v2
      with:
        version: ${{ inputs.pnpm-version }}
        run_install: false
    - name: Get pnpm store directory
      id: pnpm-store-dir
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
    - name: Setup pnpm cache
      id: pnpm-setup-cache
      uses: actions/cache@v3
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    - name: Install dependencies
      id: pnpm-install-dep
      shell: bash
      run: pnpm install --no-frozen-lockfile
