---
name: Github release
description: Releasing on Github
author: ixxeL
inputs:
  tag:
    required: true
    description: tag to use as release
  last-tag:
    required: false
    description: latest tag
  verify-tag:
    required: false
    default: "false"
    description: verify if tag exist
  target-branch:
    required: false
    default: main
    description: branch to taget
  prerelease:
    required: false
    default: "false"
    description: Mark the release as a prerelease
  auto-changelog:
    required: false
    default: "true"
    description: Auto changelog generate
  notes-file:
    required: false
    default: "true"
    description: note file or stdin

runs:
  using: composite
  steps:
    - id: gh-release
      run: |
        echo -e "${BLUE}[ STEP - RELEASE GH ] > Releasing on Github${BLANK}"
        echo -e "${CYAN}[ INFO ] > gh version.${BLANK}"
        gh --version

        echo -e "${YELLOW}[ EXECUTING ] > Releasing on tag ${{ inputs.tag }}${BLANK}"
        if [[ "${{ inputs.auto-changelog }}" == "true" ]]
        then
          gh release create ${{ inputs.tag }} --generate-notes \
                                              --latest \
                                              --verify-tag=${{ inputs.verify-tag }} \
                                              --target=${{ inputs.target-branch }} \
                                              --notes-start-tag=${{ inputs.last-tag }} \
                                              --prerelease=${{ inputs.prerelease }}
        else
          gh release create ${{ inputs.tag }} --title "Release ${{ inputs.tag }}" \
                                              --latest \
                                              --verify-tag=${{ inputs.verify-tag }} \
                                              --target=${{ inputs.target-branch }} \
                                              --notes-start-tag=${{ inputs.last-tag }} \
                                              --prerelease=${{ inputs.prerelease }} \
                                              --notes-file=${{ inputs.notes-file }}
        fi
      shell: bash
      env:
        RED: \033[1;31m
        GREEN: \033[1;32m
        YELLOW: \033[1;33m
        BLUE: \033[1;34m
        PURPLE: \033[1;35m
        CYAN: \033[1;36m
        BLANK: \033[0m
