---
name: Automate tag
on:
  workflow_call:
    secrets:
      git-token:
        required: true
    inputs:
      workingdir:
        required: false
        default: "./"
        type: string
      runs-on:
        description: OS to run jobs on
        required: false
        default: ubuntu-latest
        type: string
      ci-image:
        description: docker image to run pipeline on
        required: false
        default: ixxel/toolbox:base-latest
        type: string
      workflows-directory:
        description: directory in which to find workflows
        required: false
        default: "./.github/workflows/*.yaml"
        type: string
      actions-source:
        description: origin of actions
        required: false
        default: ixxeL-actions
        type: string
      new-ref:
        required: false
        type: string
      git-workdir:
        required: false
        default: .
        type: string
      push-option:
        required: false
        default: ci.skip
        type: string
      update-base-tag:
        required: false
        default: true
        type: boolean
      release-verify-tag:
        required: false
        default: false
        type: boolean
      release-target-branch:
        required: false
        default: ${{ github.ref_name }}
        type: string
      increment:
        required: false
        default: fix
        type: string
jobs:
  auto-tag-repo:
    name: "\U0001F680 Release"
    timeout-minutes: 5
    runs-on: ${{ inputs.runs-on }}
    # permissions:
    #   contents: read
    #   pages: write
    #   id-token: write
    container:
      image: ${{ inputs.ci-image }}
    steps:
      - name: Clone code
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"
          token: ${{ secrets.git-token }}
      - name: Git config
        id: git-config
        uses: ixxeL-DevOps/gha-templates/.github/actions/git-config@v1.2.1
        with:
          git-workdir: ${{ inputs.workingdir }}
      - name: Get last tag
        id: get-last-tag
        uses: ixxeL-DevOps/gha-templates/.github/actions/git-get-last-tag@v1.2.1
        with:
          git-workdir: ${{ inputs.workingdir }}
          branch: ${{ inputs.release-target-branch }}
      - name: Detect bump
        id: detect-bump
        uses: ixxeL-DevOps/gha-templates/.github/actions/detect-bump@v1.2.1
        with:
          release-regex: '\s*:package: CI release version ${{ steps.get-last-tag.outputs.LAST_TAG }}.+'
          minor-regex: ^(feat/.+)$
          major-regex: ^((((feat|fix|chore|docs|perf|refactor|build|ci|revert|style|test)!)|(!(feat|fix|chore|docs|perf|refactor|build|ci|revert|style|test)))/.+)$
      - name: Bump version
        id: bump-version
        uses: ixxeL-DevOps/gha-templates/.github/actions/bump-version@v1.2.1
        with:
          increment: ${{ steps.detect-bump.outputs.BUMP_KIND }}
          current-version: ${{ steps.get-last-tag.outputs.LAST_TAG != '' && steps.get-last-tag.outputs.LAST_TAG || 'v1.0.0' }}
      - name: Substitute ref
        id: substitute-ref
        uses: ixxeL-DevOps/gha-templates/.github/actions/change-action-ref@v1.2.1
        with:
          workflows-directory: ${{ inputs.workflows-directory }}
          actions-source: ${{ inputs.actions-source }}
          new-ref: ${{ steps.bump-version.outputs.VERSION }}
      - name: Update changelog
        id: changelog
        uses: ixxeL-DevOps/gha-templates/.github/actions/generate-changelog@v1.2.1
        with:
          workingdir: ${{ inputs.workingdir }}
          release-name: ${{ steps.bump-version.outputs.VERSION }}
      - name: Git push
        id: git-push
        uses: ixxeL-DevOps/gha-templates/.github/actions/git-push@v1.2.1
        with:
          git-msg: ":package: CI release version ${{ steps.bump-version.outputs.VERSION }} from user ${GITHUB_ACTOR} [skip ci]"
          git-workdir: ${{ inputs.workingdir }}
          git-staging-dir: ${{ inputs.workingdir }}
          push-option: ${{ inputs.push-option }}
      - name: GH Release
        id: gh-release
        uses: ixxeL-DevOps/gha-templates/.github/actions/gh-release@v1.2.1
        with:
          tag: ${{ steps.bump-version.outputs.VERSION }}
          verify-tag: ${{ inputs.release-verify-tag }}
          last-tag: ${{ steps.get-last-tag.outputs.LAST_TAG }}
          target-branch: ${{ inputs.release-target-branch }}
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Extract Major
        id: extract-major
        run: |
          if [[ "${{ steps.bump-version.outputs.VERSION }}" =~ ^v?[0-9]+\.[0-9]+\.[0-9]+ ]]; then
            BASE_VERSION=$(echo "${{ steps.bump-version.outputs.VERSION }}" | grep -Eo "^v?[0-9]{1}")
            echo "BASE_VERSION=$BASE_VERSION" >> $GITHUB_OUTPUT
          fi
      - name: Delete git tag
        id: git-tag-delete
        uses: ixxeL-DevOps/gha-templates/.github/actions/git-tag-delete@v1.2.1
        with:
          tag: ${{ steps.extract-major.outputs.BASE_VERSION }}
          git-workdir: ${{ inputs.workingdir }}
      - name: Git update base tag
        id: git-tag
        uses: ixxeL-DevOps/gha-templates/.github/actions/git-tag@v1.2.1
        with:
          tag-msg: "update tag semver [skip ci]"
          tag-value: ${{ steps.extract-major.outputs.BASE_VERSION }}
          git-workdir: ${{ inputs.workingdir }}
          push-option: ${{ inputs.push-option }}
          commit-sha: ${{ steps.git-push.outputs.GIT_PUSHED_COMMIT_SHA }}
      - name: Git revert to main
        id: git-revert
        uses: ixxeL-DevOps/gha-templates/.github/actions/git-revert@v1.2.1
        with:
          git-workdir: ${{ inputs.workingdir }}
          push-option: ${{ inputs.push-option }}
          commit-sha-revert: ${{ steps.git-push.outputs.GIT_PUSHED_COMMIT_SHA }}
          git-msg: ":recycle: reverted main ref [skip ci]"
