---
name: Releasing docker image
on:
  workflow_call:
    secrets:
      docker-io-pwd:
        required: false
      registry-password:
        required: false
      git-token:
        required: false
    inputs:
      # General
      release:
        required: false
        default: "false"
        type: string
      build-image:
        required: false
        default: ixxel/toolbox:builder-latest
        type: string
      workingdir:
        required: false
        default: .
        type: string
      img-name:
        required: true
        type: string
      tag:
        required: false
        type: string
      build-arg:
        required: false
        default: "CI=true"
        type: string
      target-dir:
        required: false
        default: artefacts
        type: string
      component:
        required: false
        type: string
      # docker login
      docker-config:
        required: false
        default: true
        type: boolean
      registry-url:
        required: true
        type: string
      registry-username:
        required: true
        type: string
      # podman-password:
      #   required: true
      #   type: string
      tls-verify:
        required: false
        type: boolean
      # buildkit
      dockerfile-name:
        required: false
        default: Dockerfile
        type: string
      caching:
        required: false
        default: true
        type: boolean
      cache-registry:
        required: false
        type: string
      push:
        description: Push img
        required: false
        default: true
        type: boolean
      # git tag
      git-workdir:
        required: false
        default: .
        type: string
      tag-msg:
        required: false
        default: "ci"
        type: string
      push-option:
        required: false
        default: ci.skip
        type: string
      git-email:
        required: false
        default: test@mail.com
        type: string
        # repo-url:
        #   required: true
      release-verify-tag:
        required: false
        default: false
        type: boolean
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  releasing:
    name: Build
    timeout-minutes: 15
    runs-on: ubuntu-latest
    # container:
    #   image: ${{ inputs.build-image }}
    #   options: --privileged
    steps:
      - name: Clone code
        id: clone
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"
          token: ${{ secrets.git-token }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        if: inputs.release == 'true'
        with:
          registry: ${{ inputs.registry-url }}
          username: ${{ inputs.registry-username }}
          password: ${{ secrets.registry-password }}
          logout: false
      - name: Git config
        id: git-config
        uses: ixxeL-DevOps/gha-templates/.github/actions/git-config@v0.4.1
        with:
          git-workdir: ${{ inputs.git-workdir }}
      - name: Install svu
        run: |
          wget https://github.com/caarlos0/svu/releases/download/v1.12.0/svu_1.12.0_linux_amd64.tar.gz
          tar -xzvf svu_1.12.0_linux_amd64.tar.gz
          chmod +x svu
          mv svu /usr/local/bin/
      - name: Get last tag
        id: get-last-tag
        run: |
          LAST_TAG=$(svu current --prefix="${{ inputs.component }}-v" --pattern='${{ inputs.component }}-v*')
          echo "Last version $LAST_TAG"
          echo "LAST_TAG=$LAST_TAG" >> $GITHUB_OUTPUT
      - name: Calculate new version
        id: bump-version
        run: |
          VERSION=$(svu next --prefix="${{ inputs.component }}-v" --pattern='${{ inputs.component }}-v*')
          echo "New version $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
      - name: Hadolint Dockerfile Scan
        uses: hadolint/hadolint-action@v3.1.0
        id: hadolint
        if: inputs.release == 'false'
        continue-on-error: true
        with:
          dockerfile: ${{ inputs.workingdir }}/Dockerfile
          verbose: true
          failure-threshold: info
      - name: Update PR
        uses: actions/github-script@v6
        if: inputs.release == 'false' && (github.ref != 'refs/heads/main' || github.ref != 'refs/heads/master') && github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `
            #### Hadolint: \`${{ steps.hadolint.outcome }}\`
            \`\`\`
            ${process.env.HADOLINT_RESULTS}
            \`\`\`
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      - name: Build Docker img for test
        uses: docker/build-push-action@v5
        if: inputs.release == 'false'
        with:
          context: ${{ inputs.workingdir }}
          platforms: linux/amd64
          push: false
          load: true
          sbom: false
          provenance: false
          build-args: |
            ${{ inputs.build-arg }}
          tags: |
            ${{ inputs.cache-registry }}/${{ inputs.img-name }}:${{ steps.bump-version.outputs.VERSION }}
            ${{ inputs.cache-registry }}/${{ inputs.img-name }}:latest
      - name: Build and publish Docker img
        uses: docker/build-push-action@v5
        if: inputs.release == 'true'
        with:
          context: ${{ inputs.workingdir }}
          platforms: linux/amd64
          push: true
          sbom: false
          provenance: false
          build-args: |
            ${{ inputs.build-arg }}
          tags: |
            ${{ inputs.cache-registry }}/${{ inputs.img-name }}:${{ steps.bump-version.outputs.VERSION }}
            ${{ inputs.cache-registry }}/${{ inputs.img-name }}:latest
      - name: GH Release
        id: gh-release
        uses: ixxeL-DevOps/gha-templates/.github/actions/gh-release@v0.4.1
        if: inputs.release == 'true'
        with:
          tag: ${{ steps.bump-version.outputs.VERSION }}
          target-branch: ${{ github.ref_name }}
          verify-tag: ${{ inputs.release-verify-tag }}
          last-tag: ${{ steps.get-last-tag.outputs.LAST_TAG }}
        env:
          GH_TOKEN: ${{ github.token }}
