##################################################
# DO NOT CALL DIRECTLY THIS WORKFLOW ON PROJECTS #
##################################################
#
# Automatically release new version
#
---
name: Release
on:
  workflow_call:
    secrets:
      git-token:
        required: false
    inputs:
      workingdir:
        default: .
        type: string
        required: false
      # git tag
      push-option:
        required: false
        default: ci.skip
        type: string
      git-workdir:
        required: false
        default: .
        type: string
jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    name: release
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      checks: write
      contents: write
      deployments: write
      issues: write
      id-token: write
      pull-requests: write
      statuses: write
    steps:
      - name: Clone code
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"
          token: ${{ secrets.git-token }}
      - name: Git config
        id: git-config
        uses: ixxeL-DevOps/gha-templates/.github/actions/git-config@v0.20.0-rc.5
        with:
          git-workdir: ${{ inputs.git-workdir }}
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v7
      - name: Define component in tag
        id: define-component
        run: |
          module_name=$(echo "${{ github.ref_name }}" | awk -F'-' '{print $1}')
          if [ -n "$module_name" ]
          then
            regex="${module_name}-v?[0-9]+\.[0-9]+\.[0-9]+"
          else
            regex="v?[0-9]+\.[0-9]+\.[0-9]+"
          fi
          echo "Regex : $regex"
          echo "REGEX=$regex" >> $GITHUB_OUTPUT
      - name: Get last tag
        id: get-last-tag
        uses: ixxeL-DevOps/gha-templates/.github/actions/git-get-last-tag@v0.20.0-rc.5
        with:
          git-workdir: ${{ inputs.workingdir }}
          branch: ${{ steps.branch-name.outputs.default_branch }}
          pattern: ${{ steps.define-component.outputs.REGEX }}
      - name: Update changelog
        id: changelog
        uses: ixxeL-DevOps/gha-templates/.github/actions/generate-changelog@v0.20.0-rc.5
        with:
          workingdir: ${{ inputs.workingdir }}
          lower-tag: ${{ steps.get-last-tag.outputs.BEFORE_LAST_TAG }}
          upper-tag: ${{ github.ref_name }}
      - name: GH Release
        id: gh-release
        uses: ixxeL-DevOps/gha-templates/.github/actions/gh-release@v0.20.0-rc.5
        with:
          tag: ${{ github.ref_name }}
          target-branch: ${{ steps.branch-name.outputs.default_branch }}
          verify-tag: "true"
          last-tag: ${{ steps.get-last-tag.outputs.BEFORE_LAST_TAG }}
          auto-changelog: "false"
          notes-file: ${{ inputs.workingdir }}/CHANGELOG.md
        env:
          GH_TOKEN: ${{ github.token }}
