##################################################
# DO NOT CALL DIRECTLY THIS WORKFLOW ON PROJECTS #
##################################################
#
# Automatically update a PR title
#
---
name: Update PR title
on:
  workflow_call:
    secrets:
      git-token:
        required: false
    inputs:
      build-image:
        required: false
        default: ixxel/toolbox:builder-latest
        type: string
      workingdir:
        required: false
        default: "./"
        type: string
      pr-pattern:
        required: false
        default: ${{ github.event.pull_request.head.ref }}
        type: string
      component-path-position:
        required: false
        default: 2
        type: number
jobs:
  update-pr-title:
    name: update-pr-title
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.build-image }}
    steps:
      - name: Clone code
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"
          token: ${{ secrets.git-token }}
      - name: Git config
        id: git-config
        uses: ixxeL-DevOps/gha-templates/.github/actions/git-config@v0.20.0-rc.5
        with:
          git-workdir: ${{ inputs.workingdir }}
      - name: Get last tag
        id: get-last-tag
        uses: ixxeL-DevOps/gha-templates/.github/actions/git-get-last-tag@v0.20.0-rc.5
        with:
          pattern: "*-[0-9]*.[0-9]*.[0-9]*"
          git-workdir: ${{ inputs.workingdir }}
      - name: Update PR title
        id: update-pr-title
        uses: ixxeL-DevOps/gha-templates/.github/actions/gh-update-pr-title@v0.20.0-rc.5
        with:
          pattern: ${{ inputs.pr-pattern }}
        env:
          GH_TOKEN: ${{ github.token }}
