---
name: Auto tag workflows
on:
  push:
    branches:
      - main
    paths:
      - .github/**
jobs:
  auto-tag-repo:
    uses: ixxeL-DevOps/gha-templates/.github/workflows/__new-auto-tag__.yaml@v1.2.3
    with:
      git-workdir: .github
    secrets:
      git-token: ${{ secrets.PAT }}
