---
name: Auto tag workflows
on:
  push:
    branches:
      - main
    paths:
      - .github/**
  workflow_dispatch:
jobs:
  auto-tag-repo:
    uses: ixxeL-DevOps/gha-templates/.github/workflows/__auto-tag__.yaml@v0.1.0
    with:
      git-workdir: .github
    secrets:
      git-token: ${{ secrets.PAT }}
