---
name: Docker image building
on:
  workflow_call:
    secrets:
      git-token:
        required: false
      GH_API_TOKEN:
        required: false
      DOCKER_IO_PWD:
        required: false
    inputs:
      workingdir:
        required: false
        default: .
        type: string
      build-image:
        required: false
        default: ixxel/toolbox:builder-latest
        type: string
      component:
        required: false
        type: string
      img-name:
        required: false
        type: string
      cache-registry:
        required: false
        default: docker.io/ixxel
        type: string
      registry-url:
        required: false
        default: docker.io
        type: string
      registry-username:
        required: false
        type: string
jobs:
  docker-test-build:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    if: (!contains(fromJSON('["refs/heads/master", "refs/heads/main"]'), github.ref))
    uses: ixxeL-DevOps/gha-templates/.github/workflows/__docker-release__.yaml@v0.19.0-rc.0
    with:
      component: ${{ inputs.component }}
      workingdir: ${{ inputs.workingdir }}
      img-name: ${{ inputs.img-name }}
      cache-registry: ${{ inputs.cache-registry }}
      registry-url: ${{ inputs.registry-url }}
      registry-username: ${{ inputs.registry-username }}
      publish: false
    secrets:
      git-token: ${{ secrets.git-token }}
      docker-io-pwd: ${{ secrets.DOCKER_IO_PWD }}
      registry-password: ${{ secrets.DOCKER_IO_PWD }}
  docker-full-build:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    if: contains(fromJSON('["refs/heads/master", "refs/heads/main"]'), github.ref)
    uses: ixxeL-DevOps/gha-templates/.github/workflows/__docker-release__.yaml@v0.19.0-rc.0
    with:
      component: ${{ inputs.component }}
      workingdir: ${{ inputs.workingdir }}
      img-name: ${{ inputs.img-name }}
      cache-registry: ${{ inputs.cache-registry }}
      registry-url: ${{ inputs.registry-url }}
      registry-username: ${{ inputs.registry-username }}
      publish: false
    secrets:
      git-token: ${{ secrets.git-token }}
      docker-io-pwd: ${{ secrets.DOCKER_IO_PWD }}
      registry-password: ${{ secrets.DOCKER_IO_PWD }}
