---
name: Update Pull Request title
on:
  pull_request:
    types:
      - opened
jobs:
  update-pr:
    uses: ixxeL-DevOps/gha-templates/.github/workflows/__update-PR-classic__.yaml@v0.4.6
    secrets:
      git-token: ${{ secrets.PAT }}
