---
name: Check GH actions templates
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - "main"
jobs:
  check-gha-templates:
    uses: ixxeL-DevOps/gha-templates/.github/workflows/__check-gha-templates__.yaml@v0.6.2
