---
name: Release GHA templates
on:
  workflow_dispatch:
jobs:
  release-gha-tpl:
    uses: ixxeL-DevOps/gha-templates/.github/workflows/__release-gha-tpl__.yaml@v0.16.0
    with:
      git-workdir: .github
    secrets:
      git-token: ${{ secrets.PAT }}
