---
name: Terraform
on:
  workflow_call:
    secrets:
      git-token:
        required: false
    inputs:
      workingdir:
        required: false
        default: .
        type: string
      environment:
        required: false
        default: dev
        type: string
jobs:
  terraform:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    uses: ixxeL-DevOps/gha-templates/.github/workflows/__terraform__.yaml@v0.23.0
    with:
      workingdir: ${{ inputs.workingdir }}
      environment: ${{ inputs.environment }}
    secrets:
      git-token: ${{ secrets.git-token }}
