---
name: Terragrunt
on:
  workflow_call:
    secrets:
      git-token:
        required: false
    inputs:
      workingdir:
        required: false
        default: .
        type: string
      environment:
        required: false
        default: dev
        type: string
      tg-version:
        required: false
        default: "0.56.3"
        type: string
      tf-version:
        required: false
        default: "1.7.5"
        type: string
jobs:
  terragrunt:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    uses: ixxeL-DevOps/gha-templates/.github/workflows/__terragrunt__.yaml@v0.22.1
    with:
      workingdir: ${{ inputs.workingdir }}
      environment: ${{ inputs.environment }}
      tf-version: ${{ inputs.tf-version }}
      tg-version: ${{ inputs.tg-version }}
    secrets:
      git-token: ${{ secrets.git-token }}
