---
name: update PR title
on:
  workflow_call:
    secrets:
      git-token:
        required: false
jobs:
  update-pr-title:
    uses: ixxeL-DevOps/gha-templates/.github/workflows/__update-PR__.yaml@v0.1.0
    secrets:
      git-token: ${{ secrets.git-token }}
